# Generated by Django 5.2.3 on 2025-07-17 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto')], max_length=10)),
                ('symbol', models.CharField(max_length=10)),
                ('units', models.DecimalField(decimal_places=6, max_digits=12)),
                ('buy_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
