# Generated by Django 5.2.4 on 2025-07-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(help_text='Phone number in format 2547XXXXXXXX', max_length=13),
        ),
    ]
