# Generated by Django 5.2.4 on 2025-07-21 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_alter_mpesatransaction_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'M-Pesa Transaction', 'verbose_name_plural': 'M-Pesa Transactions'},
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='account_reference',
            field=models.CharField(blank=True, help_text='Account reference used during STK Push', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount transacted via M-Pesa', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(help_text='Unique CheckoutRequestID from Safaricom', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when transaction was created'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or transaction note', null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, help_text='MerchantRequestID from Safaricom', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text='Receipt number from successful M-Pesa transaction', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='result_code',
            field=models.CharField(blank=True, help_text='Safaricom ResultCode (e.g., 0 for success)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='result_desc',
            field=models.CharField(blank=True, help_text='Safaricom ResultDesc (result description)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the transaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when transaction was last updated'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='user',
            field=models.ForeignKey(help_text='The user who initiated the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
