# Generated by Django 5.2.4 on 2025-07-21 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0003_loan_interest_rate_loan_total_due'),
        ('mpesa', '0003_alter_mpesatransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activate_user', 'Activate User'), ('deactivate_user', 'Deactivate User'), ('approve_loan', 'Approve Loan'), ('reject_loan', 'Reject Loan'), ('freeze_wallet', 'Freeze Wallet'), ('unfreeze_wallet', 'Unfreeze Wallet')], help_text='The type of admin action performed', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the action was performed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context about the action')),
                ('admin_user', models.ForeignKey(help_text='The admin who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, help_text='The loan affected by the admin action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loan')),
                ('target_user', models.ForeignKey(blank=True, help_text='The user affected by the admin action (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_users', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, help_text='The transaction affected by the admin action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpesa.mpesatransaction')),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
