# Generated by Django 5.2.3 on 2025-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_transfer_pin_transactionhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
