# Generated by Django 5.2.3 on 2025-07-17 10:35

import loans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='repayment_date',
            field=models.DateField(default=loans.models.default_repayment_date),
        ),
    ]
